dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

install:
  - npm install

before_script:
  - npm run build
  - npm run pre-test

script:
  - npm run lint
  - npm run test

after_success: npm run coverage